### ISSUE TITLE
Inconsistent Circle-CI Build Failure trying to Download Chromium

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2215]
**Describe the bug**
What went wrong? What did you expect to happen?
Almost everytime we run a Circle-CI build, it fails on on the **docker build -f Dockerfile.cypress -t ld4l/sinopia_editor_cypress.** step with the following error

```Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-57_binding.node
 
Download complete
Binary saved to /node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /root/.npm/node-sass/4.14.1/linux-x64-57_binding.node
 
> puppeteer@2.1.1 install /node_modules/puppeteer
 
> node install.js
 
ERROR: Failed to download Chromium r722234! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
 
Error: end of central directory record signature not found
    at /node_modules/yauzl/index.js:187:14
    at /node_modules/yauzl/index.js:631:5
    at /node_modules/yauzl/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)

  -- ASYNC --
    at BrowserFetcher.<anonymous> (/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/node_modules/puppeteer/install.js:66:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
``` 

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
Workaround is re-run the failed step in Circle-CI.

- What environment are you in? (stage or production). n/a
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
n/a
- If you're cataloging, what Resource Template were you using (name or ID)

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

**Comment by jermnelson** [comment]
Believe this is related https://github.com/puppeteer/puppeteer/issues/2173. I went ahead and created a new CircleCI ENV variable `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` set to true and so far the builds are passing. I'll keep monitoring to see if builds continue to succeed. If so, will close this issue.

**Comment by jermnelson** [comment]
Closing, not seeing this error any more in the Sinopia Editor builds.
